//! Format-specific handlers

use crate::{error::Result, structure::Structure, Updates};
use std::io::{Read, Seek, Write};

// Forward declare Format here so handlers can use it
// The actual enum is generated by register_formats! macro
pub use crate::Format;

/// Trait for format-specific file handlers
pub trait FormatHandler: Send + Sync {
    /// Formats this handler supports
    fn supported_formats() -> &'static [Format]
    where
        Self: Sized;

    /// File extensions this handler accepts (e.g., ["jpg", "jpeg"])
    fn extensions() -> &'static [&'static str]
    where
        Self: Sized;

    /// MIME types this handler accepts
    fn mime_types() -> &'static [&'static str]
    where
        Self: Sized;

    /// Try to detect if this handler can parse the given header
    /// Returns Some(Format) if confident, None if unsure
    fn detect(header: &[u8]) -> Option<Format>
    where
        Self: Sized;

    /// Parse file structure in single pass
    ///
    /// This discovers all segments, XMP, and JUMBF locations without
    /// loading the actual data into memory.
    fn parse<R: Read + Seek>(&self, reader: &mut R) -> Result<Structure>;

    /// Write file with updates in single streaming pass
    ///
    /// This streams from the source to destination, applying updates
    /// without loading the entire file into memory.
    fn write<R: Read + Seek, W: Write>(
        &self,
        structure: &Structure,
        reader: &mut R,
        writer: &mut W,
        updates: &Updates,
    ) -> Result<()>;

    /// Extract XMP data from file (format-specific)
    ///
    /// This handles format-specific details like JPEG's extended XMP
    /// with multi-segment assembly, or PNG's simple iTXt chunks.
    fn extract_xmp<R: Read + Seek>(
        &self,
        structure: &Structure,
        reader: &mut R,
    ) -> Result<Option<Vec<u8>>>;

    /// Extract JUMBF data from file (format-specific)
    ///
    /// This handles format-specific details like JPEG XT headers,
    /// multi-segment assembly, etc.
    fn extract_jumbf<R: Read + Seek>(
        &self,
        structure: &Structure,
        reader: &mut R,
    ) -> Result<Option<Vec<u8>>>;

    /// Extract embedded thumbnail from format-specific metadata
    ///
    /// Some formats embed pre-rendered thumbnails in their metadata:
    /// - JPEG: EXIF IFD1 thumbnail (typically ~160x120)
    /// - HEIF: 'thmb' item reference
    /// - WebP: VP8L thumbnail chunk
    /// - PNG: No embedded thumbnails (returns None)
    ///
    /// This is the fastest thumbnail path - no decoding needed!
    #[cfg(feature = "exif")]
    fn extract_embedded_thumbnail<R: Read + Seek>(
        &self,
        structure: &Structure,
        reader: &mut R,
    ) -> Result<Option<crate::EmbeddedThumbnail>>;
}

// Format modules are private - handlers are re-exported at crate root
#[cfg(feature = "jpeg")]
pub(crate) mod jpeg;

#[cfg(feature = "png")]
pub(crate) mod png;
